importer:
  folder: files-to-process
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
    template:
      exchange: